# Generated by Django 4.2 on 2024-05-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["order"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок урока в материале"
            ),
        ),
    ]
