# Generated by Django 4.2 on 2024-05-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_alter_lesson_options_lesson_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Порядок урока в материале"
            ),
        ),
    ]
