# Generated by Django 4.2 on 2024-04-07 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("single_choices", "одиночный выбор"),
                            ("multiple_choices", "множественный выбор"),
                            ("input", "ввод ответа"),
                        ],
                        verbose_name="Тип вопроса",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст вопроса")),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.CreateModel(
            name="Testing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=128, verbose_name="Заголовок теста"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Необязательно",
                        null=True,
                        verbose_name="Описание теста",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="lessons.lesson",
                        verbose_name="Урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест по уроку",
                "verbose_name_plural": "Тесты по урокам",
            },
        ),
        migrations.CreateModel(
            name="UserTestStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentage_of_correct_answers",
                    models.FloatField(
                        default=0.0, verbose_name="Процент правильных ответов"
                    ),
                ),
                (
                    "testing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_testings",
                        to="testings.testing",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_statistics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика пользователя по тесту",
                "verbose_name_plural": "Статистики пользователей по тестам",
            },
        ),
        migrations.CreateModel(
            name="UserQuestionTestStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_variant",
                    models.CharField(
                        max_length=256, verbose_name="Вариант пользователя"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_statistics",
                        to="testings.question",
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "test_statistic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testings.userteststatistics",
                        verbose_name="Статистика по тесту",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_test_statistics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика пользователя по вопросу теста",
                "verbose_name_plural": "Статистики пользователей по вопросам тестов",
            },
        ),
        migrations.AddField(
            model_name="testing",
            name="users_statistics",
            field=models.ManyToManyField(
                through="testings.UserTestStatistics", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="testing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="testings.testing",
                verbose_name="Тест",
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст варианта овтета")),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="testings.question",
                        verbose_name="Связанный вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответа",
            },
        ),
    ]
