# Generated by Django 4.2 on 2024-04-29 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("single_choices", "одиночный выбор"),
                    ("multiple_choices", "множественный выбор"),
                    ("input", "ввод ответа"),
                    ("relation", "соответствие"),
                ],
                verbose_name="Тип вопроса",
            ),
        ),
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Текст")),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to="answers/images",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="testings.answer",
                        verbose_name="Соответствие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Соответствие",
                "verbose_name_plural": "Соответствие",
            },
        ),
    ]
