# Generated by Django 4.2 on 2024-05-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testings", "0004_alter_answer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestionteststatistics",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="Верно"),
        ),
    ]
