version: '3.8'

services:
  backend:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/:cached
      - static:/app/static:delegated
      - media:/app/media:delegated
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - memcached

  db:
    image: postgres:16.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_NAME=$POSTGRES_NAME

  celery:
    command: celery -A config worker -l info -c 1 -Q celery
    build:
      context: ./backend
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$CELERY_RESULT_BACKEND
    depends_on:
      - db
      - redis

  redis:
    image: redis:6.2-alpine
    volumes:
      - redisdata:/data

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    command: [ "memcached" ]

volumes:
  postgres_data:
  redisdata:
  static:
  media:
