version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:${FRONTEND_PORT}:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static:/app/static
      - media:/app/media
    expose:
      - 8000
    env_file:
      - ./.env
    environment:
      - DEBUG=false
    depends_on:
      - db
      - memcached

  db:
    image: postgres:16.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_NAME=$POSTGRES_NAME

  celery:
    command: celery -A config worker -l info -c 1 -Q celery
    restart: always
    build:
      context: ./backend
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND=$CELERY_RESULT_BACKEND
    depends_on:
      - db
      - redis

  redis:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - redisdata:/data

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    command: [ "memcached" ]

volumes:
  postgres_data:
  static:
  media:
  redisdata:
