# Generated by Django 4.2 on 2024-04-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="materials/images",
                verbose_name="Превью",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="short_description",
            field=models.TextField(
                blank=True, max_length=568, null=True, verbose_name="Короткое описание"
            ),
        ),
    ]
